#pragma once

enum cursor_shape {
    CURSOR_SHAPE_NONE,
    CURSOR_SHAPE_CUSTOM,

    CURSOR_SHAPE_HIDDEN,
    CURSOR_SHAPE_LEFT_PTR,
    CURSOR_SHAPE_TEXT,
    CURSOR_SHAPE_TEXT_FALLBACK,
    CURSOR_SHAPE_TOP_LEFT_CORNER,
    CURSOR_SHAPE_TOP_RIGHT_CORNER,
    CURSOR_SHAPE_BOTTOM_LEFT_CORNER,
    CURSOR_SHAPE_BOTTOM_RIGHT_CORNER,
    CURSOR_SHAPE_LEFT_SIDE,
    CURSOR_SHAPE_RIGHT_SIDE,
    CURSOR_SHAPE_TOP_SIDE,
    CURSOR_SHAPE_BOTTOM_SIDE,
};

const char *cursor_shape_to_string(enum cursor_shape shape);
